apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: namespacesets.example.com
spec:
  group: example.com
  scope: Cluster
  names:
    plural: namespacesets
    singular: namespaceset
    kind: NamespaceSet
    shortNames:
      - nset
  versions:
    - name: v1
      served: true
      storage: true
      schema:
        openAPIV3Schema:
          type: object
          properties:
            spec:
              type: object
              properties:
                teams:
                  type: array
                  items:
                    type: object
                    properties:
                      name:
                        type: string
                      email:
                        type: string
                      namespaces:
                        type: array
                        items:
                          type: string
                      resourceQuota:
                        type: object
                        properties:
                          hard:
                            type: object
                            additionalProperties:
                              type: string
      subresources:
        status: {}
